### ISSUE TITLE
Signature format inconsistency

### ISSUE THREAD

**Issue by wiktor-k** [firstlookmedia/keylist-rfc#10]
Hello,

I've been reading the RFC and noticed that [section 3.2](https://tools.ietf.org/html/draft-mccain-keylist-01#section-3.2) requires ASCII-armored signatures:

```
3.2.  Signature

   The signature file MUST be an ASCII-armored 'detached signature' of
   the keylist file, as defined in OpenPGP Message Format [RFC4880] .
```

while [Firstlook's keylist](https://github.com/firstlookmedia/gpgsync-firstlook-fingerprints) signature looks like a binary file.

Is there a reason ASCII-armored signatures are required in the I-D? It seems binary ones would be better as they are smaller.

**Comment by micahflee** [comment]
The First Look keylist doesn't yet comply with the latest version of the RFC. We're actually about to completely change the keylist file format too (#8, #9), and it will take some time to update our keylist file as well as GPG Sync to use this new format.

We discussed whether the signature should be binary or ASCII-armored and decided on ASCII-armored because it makes it simpler to host in various environments. For example, you can host an ASCII sig in a GitHub gist, or on pastebin, but you can't host a binary sig like that.

I just made both types of detached sigs. The difference in file size between a binary and ASCII sig is pretty small (267 bytes, in my test):

```
$ ls -l
total 32
-rw-rw-r-- 1 user user 22033 Oct  8 09:24 fingerprints.txt
-rw-rw-r-- 1 user user   833 Oct  8 09:25 fingerprints.txt.asc
-rw-rw-r-- 1 user user   566 Oct  8 09:25 fingerprints.txt.sig
```

As the keylist file grows in size, the signature will remain the same size. So because it can be hosted in more places, I like the idea of keeping ASCII-armored sigs. Of course, it would be easy to support both types.

Is there a good reason to support binary sigs as well, other than the fact that it saves a tiny bit of disk space/bandwidth?

**Comment by wiktor-k** [comment]
Thanks for the explanation @micahflee, it makes more sense now!

I'll read the other issues for more context and get back with questions :)
