### ISSUE TITLE
Keys should be deactivatable through keylists

### ISSUE THREAD

**Issue by yahesh** [firstlookmedia/keylist-rfc#7]
We're a 100 people company that also decided to roll out GPG several years ago. As we've learned, just creating a way to retrieve the keys of all employees is not enough - especially with people who are not tech-savvy.

People will lose their key material. And not all of them will have a revocation certificate at hand to revoke their now defunct key. Even if you have organizational rules in place there will be that one exception to the rule. That's why we added a possibility to forcefully deactivate and re-enable keys through our own, internal GPG key syncing tool.

I'd love to see this RFC draft to become a standard and would be happy to switch to it, but it would be even nicer to replace our internal GPG key syncing tool completely instead of just partially.

**Comment by milesmcc** [comment]
This is a very useful suggestion. It does raise questions about how 'trusted' the keylist should be, though. I can see someone potentially raising the issue that allowing keys to be deactivated/removed via keylists might harm security because it would allow the central operator of the keylist to actively remove keys from others' machines without the consent of the key owner. (Currently, all that the owner could do is remove the key from the keylist, in which it would still be present on all the machines that it already exists on.)

From an operational perspective, I wonder if it makes sense to just ask employees to give the company a revocation certificate that the company then stores on their own machine (or on a thumb drive in a safe somewhere). This would prevent the issue of a user losing their key and being unable to issue a revoke certificate, while also keeping revocation/deactivation functionality separate from the keylist.

I'd love to hear your thoughts. In any case, thank you for this idea and let's absolutely explore it further.

**Comment by yahesh** [comment]
There shouldn't be the possibility to _remove_ keys from the keyring of the user as this action is potentially irreversible. _Disabling_ a key - in contrast - is a reversible operation as keys can also be _re-enabled_.

IMHO _adding_ keys to the keyring of the user is the action that is the most harmful one. This is the action that allows an attacker to plant illegitimate keys and thus recover messages when they're encrypted for the wrong recipient's encryption key and are trusted from the wrong sender's signing key. This is the action that potentially breaks the integrity and confidentiality of GPG.

_Disabling_ keys, by contrast, is "just" able to break availability. It potentially prevents you from encrypting sth. for a recipient or from verifying sth. from a sender.

_Re-enabling_ keys on the hand might break integrity and confidentiality as well. However, this is "only" true for keys that have already been _added_ to the keyring of the user. Only harmful keys that have been _added_ to the keyring of the user may also be harmful when they're _re-enabled_.

As to the organizational practice of requesting revocation certificates for each generated key: We've done that. When we onboarded people to the company we had a session with them where we created their key together, uploaded the key to a keyserver, generated the corresponding revocation certificate, printed it out and put into the employee's personnel file. However, there have been situations where an employee silently created a new keypair - for example they lost the keyphrase for their old keypair and thought that it would be best to just have a frest keypair that works again. In one instance we didn't notice that until that employee lost the keypair's passphrase yet again. Only then where we informed and saw what that employee had done. That was when we saw that filing employees' recovation certificates doesn't always work as long as they're able to create new keypairs on their own.

Furthermore, it might become impractical in bigger corporations to collect and file employees' revocation certificates as this adds quite a bit of organizational strain.

**Comment by micahflee** [comment]
Hello @yahesh, I'm curious what company you work for that has 100 PGP users? First Look Media also has dozens of PGP users, so we probably run into similar issues.

We've been using [GPG Sync](https://github.com/firstlookmedia/gpgsync) internally for years now. The Keylist RFC project was basically inspired by wanting it to be possible for GPG Sync to be more integrated into more email clients, including those that don't use GPG, like on mobile or in the browser.

From the GPG Sync wiki page explaining [How is GPG Sync different than S MIME or Certificate Authorities?](https://github.com/firstlookmedia/gpgsync/wiki/How-is-GPG-Sync-different-than-S-MIME-or-Certificate-Authorities%3F):

> GPG Sync does one thing: Makes sure members of an organization always have up-to-date public keys from a centrally-managed list.
> 
> Unlike with S/MIME or CAs, users don't need to trust the central authority. At worst, a malicious authority could make you download fake public keys. If you manually verify fingerprints and sign keys, your OpenPGP software should pick the correct key to encrypt to each time. If you don't manually verify fingerprints and sign keys, then at least you won't be automatically encrypting to people's old revoked keys, and you'll get the latest keys for new members of your organization without having to manually find them and import them.

I do agree with @milesmcc that allowing the keylist to disable keys would require trusting the central authority more. For example, many of the First Look Media PGP users use Apple Mail with the GPGMail plugin, that comes with GPG Tools. In Apple Mail, when you send an email to someone and don't have a valid key for them (including if the key is disabled), it silently falls back to plaintext.

I could see an attack where someone silently disables everyone's PGP keys in our organization to be a much bigger problem (much of our internal email would suddenly drop to plaintext) than one where someone silently gets everyone to import malicious keys for everyone else. Because we have the authority key cross-sign everyone's keys and there's a trust relationship, the malicious keys won't be used.

So I think I'm in favor of not building in key disabling features into the Keylist RFC, and instead relying on revoking keys (and being careful to keep track of revokation certificates) when disabling keys is necessary.
